Blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path("" , Home.as_view() , name = "Home" ) ,
    path("about/" , About.as_view() , name = "About") ,
    
    path('articulo/nuevo/', ArticuloCreateView.as_view(), name='Crear'),
    path('articulo/listar/', ArticuloListView.as_view(), name='Listado'),
    path('articulo/<int:pk>/', ArticuloDetailView.as_view(), name='Detalles'),
    path('articulo/<int:pk>/editar/', ArticuloUpdateView.as_view(), name='Editar'),
    path('articulo/<int:pk>/eliminar/', ArticuloDeleteView.as_view(), name='Borrar'),
]

Usuarios/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    
    path( "Crear/" , Creacion_Usuario.as_view() , name = 'Crear_Usuario' ) ,
    path( "Iniciar/" , LoginView.as_view( template_name = 'usuarios/login.html' ) , name = 'Iniciar_Sesion' ) ,
    path( "Cerrar/" , LogoutView.as_view() , name='Cerrar_Sesion') ,
    path( "Editar/<int:pk>" , Editar_Usuario.as_view() , name = 'Editar_Usuario' ) ,
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Blog.urls')),
    path('usuarios/', include('Usuarios.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Articulos(models.Model):
    Titulo = models.CharField( max_length = 150 )
    Subtitulo = models.CharField( max_length = 150 )
    Contenido = models.TextField( max_length = 2000 )
    Imagen = models.ImageField( upload_to = 'Articulos/' , blank=True , null=True)
    Fecha = models.DateTimeField( auto_now = True )
    Autor = models.ForeignKey(User, on_delete=models.CASCADE)

Usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class Avatar( models.Model ):

    User = models.OneToOneField( User , on_delete=models.CASCADE)
    Imagen = models.ImageField( upload_to = 'Avatar/' )

    def save(self, *args, **kwargs):
        try:
            this = Avatar.objects.get(id=self.id)
            if this.Imagen != self.Imagen:
                this.Imagen.delete(save=False)
        except: pass # cuando se crea una nueva imagen, no existe aún
        super(Avatar, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.Imagen.delete(save=False)
        super(Avatar, self).delete(*args, **kwargs)


Blog/forms.py
from django import forms
from .models import Articulos

class ArticuloForm(forms.ModelForm):
    class Meta:
        model = Articulos
        fields = ['Titulo', 'Subtitulo', 'Contenido', 'Imagen']

Usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class Usuario_Form(UserCreationForm):
    avatar = forms.ImageField(required=False)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')

        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Este nombre de usuario ya está en uso.')

        return cleaned_data

    def save(self, commit=True):
        user = super(Usuario_Form, self).save(commit=False)
        avatar_data = self.cleaned_data.get('avatar')

        if commit:
            user.save()

        if avatar_data:
            avatar = Avatar(User=user, Imagen=avatar_data)
            if commit:
                avatar.save()

        return user


class Usuario_Form_2(forms.ModelForm):
    avatar = forms.ImageField(required=False)
    password = forms.CharField(required=True, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name' , 'last_name', 'username', 'email', 'password', 'avatar']

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get('password')
        avatar_data = self.cleaned_data.get('avatar')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        if avatar_data:
            avatar, created = Avatar.objects.get_or_create(User=user)
            avatar.Imagen = avatar_data
            if commit:
                avatar.save()

        return user





Blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
from django.urls import reverse_lazy
from .models import *
from .forms import *
# Create your views here.

class Home(View):

    def get(self, request):
        return render(request, 'base/home.html')
    
class About(View):

    def get(self, request):
        return render(request, 'blog/About.html')

class ArticuloListView(ListView):
    model = Articulos
    template_name = 'blog/articulos/articulo_list.html'
    

class ArticuloDetailView(DetailView):
    model = Articulos
    template_name = 'blog/articulos/articulo_detail.html'

class ArticuloCreateView(LoginRequiredMixin, CreateView):
    model = Articulos
    form_class = ArticuloForm
    login_url = 'Iniciar_Sesion'
    template_name = 'blog/articulos/articulo_form.html'
    success_url = reverse_lazy('Listado')

    def form_valid(self, form):
        form.instance.Autor = self.request.user
        return super().form_valid(form)

class ArticuloUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Articulos
    form_class = ArticuloForm
    template_name = 'blog/articulos/articulo_form.html'
    success_url = reverse_lazy('Listado')

    def test_func(self):
        usuario_actual = self.request.user
        return usuario_actual == self.get_object().Autor or usuario_actual.is_superuser

class ArticuloDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Articulos
    template_name = 'blog/articulos/articulo_confirm_delete.html'
    success_url = reverse_lazy('Listado')

    def test_func(self):
        usuario_actual = self.request.user
        return usuario_actual == self.get_object().Autor or usuario_actual.is_superuser


Usuarios/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from .models import *
from .forms import *

from django.contrib.auth.mixins import LoginRequiredMixin



from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

#Usuarios

class Creacion_Usuario( CreateView ):

    model = User
    form_class = Usuario_Form
    template_name = 'usuarios/crear.html'
    success_url = reverse_lazy('Home')

class Editar_Usuario( LoginRequiredMixin , UpdateView ):

    model = User
    form_class = Usuario_Form_2
    template_name = 'usuarios/editar.html'
    success_url = reverse_lazy('Home')

    

templates/base/base.html
<!DOCTYPE html>
<html lang="spanish">

<head>
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>base</title>
    <style>
    .navbar {
    font-size: 20px; /* Ajusta este valor a tu gusto */
    
    }

    .nav-item {
        padding: 15px; /* Ajusta este valor a tu gusto */
    }
    </style>
</head>

<body style="padding-top: 100px;">

    <nav class="navbar navbar-expand-lg bg-light fixed-top" data-bs-theme="light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'Home' %}"><em>LauryBlogs</em></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'Home' %}">Inicio
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Crear' %}">Publicar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Listado' %}">Navegar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'About' %}">Sobre mí</a>
                    </li>
                </ul>

                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        {% if user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            <img src="{{ user.avatar.Imagen.url }}" alt="Avatar" width="30" height="30">
                            Cuenta
                        </a>
                        {% else %}
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Cuenta
                        </a>
                        {% endif %}
                        <div class="dropdown-menu dropdown-menu-end">
                            {% if user.is_authenticated %}
                                <!-- Mostrar imagen del avatar si el usuario está autenticado -->
                                <!-- Otras opciones de cuenta para usuario autenticado -->
                                <a class="dropdown-item" href="{% url 'Editar_Usuario' user.pk %}">Perfil</a>
                                <a class="dropdown-item" href="{% url 'Cerrar_Sesion' %}">Cerrar sesión</a>
                            {% else %}
                                <!-- Opciones de cuenta para usuario no autenticado -->
                                <a class="dropdown-item" href="{% url 'Iniciar_Sesion' %}">Iniciar sesión</a>
                                <a class="dropdown-item" href="{% url 'Crear_Usuario' %}">Crear cuenta</a>
                            {% endif %}
                        </div>
                    </li>
                    
                </ul>

            </div>
        </div>
    </nav>
    
    

    {% block titulo %}
    {% endblock %}

    {% block cuerpo %}
    {% endblock %}
</body>

</html>

templates/base/home.html
{% extends "base/base.html" %}

{% block titulo %}


<header style="text-align: center; margin: 20px;">
    <h1>¡Bienvenidos a Lau Blogs!</h1>
    <h2>Estamos emocionados de tenerte aquí.</h2>  
</header>


{% endblock %}




{% block cuerpo %}

<body>
    <p style="text-align: center; margin: 40px;">Estás a punto de sumergirte en un sin fin de artículos emocionantes sobre todos los temas que te puedas imaginar. <br>
    Desde viajes por el mundo hasta tips para entrenar a un mono. <br> ¿Que esperas para sumergirte en nuestro novedoso contenido?</p>
</body>

{% endblock %}

templates/blog/About.html
{% extends "base/base.html" %}
{% load static %}
{% block titulo %}


<header style="text-align: center;">
    <img src="{% static 'assets/Yo.jpg' %}" alt="">
    <h1>LAURA MORALES</h1>
    <h2>Full Stack Developer</h2> 
    
</header>


{% endblock %}




{% block cuerpo %}

<body style="text-align: center;">

    <div class="container-fluid contact" style="text-align: center;">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 infocontacto">
                <div>  
                    <h2>Contáctame</h2>
                    <p><strong>Dirección:</strong> Piedras 1497, Buenos Aires<br>CP 1140, Argentina</p>
                    <p><strong>Celular:</strong> <a href="tel:+5491153150461">+54 9 11 5315 0461</a></p>
                    <p><strong>E-mail:</strong> <a href="mailto:info@laura-morales.com.ar">info@laura-morales.com.ar</a></p>
                </div>
                <a href="https://www.facebook.com/AGENCIA-DE-PROMOTORAS-Y-MODELOS-LAURA-MORALES-333173767406/" title="facebook">
                    <i class="fab fa-facebook"></i>
                </a>
                <span style="margin-right: 15px;"></span> 
                <a href="https://twitter.com/agciapromotoras" title="twitter">
                    <i class="fab fa-twitter"></i>
                </a>
                <span style="margin-right: 15px;"></span> 
                <a href="https://www.instagram.com/lm_promotorasymodelos/" title="instagram">
                    <i class="fab fa-instagram"></i>
                </a>
            </div>
        </div>
    </div>
    
    
     
</body>

{% endblock %}

templates/blog/articulos/articulo_confirm_delete.html
{% extends "base/base.html" %}

{% block cuerpo %}
  <h1>Eliminar Artículo</h1>
  <p>¿Estás seguro de que quieres eliminar "{{ articulo.Titulo }}"?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
  </form>

  <a href="{% url 'Detalles' pk=articulos.pk %}">Cancelar</a>
{% endblock %}

templates/blog/articulos/articulo_detail.html
{% extends "base/base.html" %}

{% block cuerpo %}

  <h1>{{ articulos.Titulo }}</h1>
  {% if articulo.Imagen %}
  <img src="{{ articulos.Imagen.url }}" alt="{{ articulo.Titulo }}">
  {% endif %}
  <h2>{{ articulos.Subtitulo }}</h2>
  <p>{{ articulos.Contenido }}</p>
  <p>Autor: {{ articulos.Autor }}</p>
  <p>Fecha: {{ articulos.Fecha }}</p>

  {% if user.is_authenticated %}
    {% if user == articulos.Autor or user.is_superuser %}
    <a href="{% url 'Editar' pk=articulos.pk %}">Editar artículo</a>
    <a href="{% url 'Borrar' pk=articulos.pk %}">Eliminar artículo</a>
    {% endif %}
  {% endif %}
{% endblock %}

templates/blog/articulos/articulo_form.html
{% extends "base/base.html" %}

{% block cuerpo  %}
  <h1>Nuevo Artículo</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
{% endblock %}

templates/blog/articulos/articulo_list.html
{% extends "base/base.html" %}

{% block cuerpo %}
  <h1>Lista de Artículos</h1>

  {% if articulos_list %}
    {% for articulo in articulos_list %}
      <div>
        <h2>{{ articulo.Titulo }}</h2>
        {% if articulo.Imagen %}
        <img src="{{ articulo.Imagen.url }}" alt="{{ articulo.Titulo }}">
        {% endif %}
        <p>{{ articulo.Subtitulo }}</p>
        <a href="{% url 'Detalles' pk=articulo.pk %}">Ver artículo</a>
      </div>
    {% endfor %}
  {% else %}
    <p>No hay artículos disponibles.</p>
  {% endif %}
{% endblock %}

templates/usuarios/crear.html
{% extends "base/base.html" %}

{% block titulo %}


<header style="text-align: center;">
    <h1>Crear Usuario</h1>    
</header>


{% endblock %}




{% block cuerpo %}

<body>
    
    <form action="" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {{form.as_p}}

        <button type="submit">Crear</button>
    </form>

</body>

{% endblock %}

templates/usuarios/editar.html
{% extends "base/base.html" %}

{% block titulo %}


<header style="text-align: center;">
    <h1>Editar Perfil</h1>    
</header>


{% endblock %}




{% block cuerpo %}

<body>
    
    <form action="" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {{form.as_p}}

        <button type="submit">Editar</button>
    </form>

</body>

{% endblock %}

templates/usuarios/login.html
{% extends "base/base.html" %}

{% block titulo %}


<header style="text-align: center;">
    <h1>Iniciar Sesión</h1>    
</header>


{% endblock %}




{% block cuerpo %}

<body>
    
    <form action="" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {{form.as_p}}

        <button type="submit">Iniciar</button>
    </form>

</body>

{% endblock %}